[[deployment]]
name = "backup-databases"
tags = ["backup"]
[deployment.config]
server = "localhost"
image.type = "Image"
image.params.image = "ghcr.io/realorangeone/db-auto-backup:latest"
image_registry_account = "b-"
network = "none"
volumes = """
/var/run/docker.sock:/var/run/docker.sock:ro
/etc/komodo/backups:/var/backups
"""
environment = """
  # VARIABLE = value
SCHEDULE=
INCLUDE_LOGS=true
"""

##

[[action]]
name = "backup-all-servers"
tags = ["backup"]
[action.config]
file_contents = """
/*// Run actions using the pre initialized 'komodo' client.
const version: Types.GetVersionResponse = await komodo.read('GetVersion', {});
console.log('🦎 Komodo version:', version.version, '🦎\n');
const BRANCH = "1.17.0";
const VERSION = "1.17.0";
const TAG = "dev-7";

*/

var deployment = await komodo.read("GetDeployment", {
  deployment: "backup-once"
});

const servers = await komodo.read("ListServers", { query: { tags: [] } });

for (const server of servers) {
  /*await komodo.write("UpdateBuild", {
    id: build.id,
    config: { version: VERSION as any, branch: BRANCH },
  });*/
  console.log("Deploying backup-once to: ", server);
  await komodo.write("UpdateDeployment", {
    id: deployment.name,
    config: {
      server_id: server.id
    }
  }
  );
  await komodo.execute_and_poll("Deploy",{deployment: deployment.name});
  var deploymentLogResponse = await komodo.read("GetDeploymentLog",{
    deployment: deployment.name,
    tail: 100,
    timestamps: true
    });
  console.log(deploymentLogResponse.stdout,deploymentLogResponse.stderr)

}
/*
await komodo.write("CommitSync", { sync: "dev" });
console.log("Committed changes to 'dev' Sync");

await komodo.execute("RunProcedure", { procedure: "build-dev" });
console.log("Launched 'build-dev' Procedure");
*/"""

##

[[resource_sync]]
name = "backups"
tags = ["backup"]
[resource_sync.config]
repo = "b-/komodo-backups"
git_account = "b-"
resource_path = ["backups.toml"]
managed = true
match_tags = ["backup"]
